Eagles.LMS/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Eagles.LMS.Models
{
    public class Category
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        public  ICollection<Types> Types { get; set; }

        public ICollection<SubItem> SubItem { get; set; }
        public  ICollection<Car> Cars { get; set; }
        public string MainImageOne { get; set; }
        public string MainImageTwo { get; set; }


        public bool ShowInBodyType { get; set; }
        [NotMapped]
        public int Count { get; set; }
        //public List<ServiceImages> ServiceImages { get; set; }

        //public DateTime CreateTime { get; set; }

        //public DateTime EditeTime { get; set; }
        //public int UserEditId { get; set; }

        //public DateTime CreateTime { get; set; }
        //public int UserCreateId { get; set; }

        //public DateTime EditeTime { get; set; }
        //public int UserEditId { get; set; }

    }
}

Eagles.LMS/Areas/Admission/Controllers/CategorysController.cs
using Eagles.LMS.BLL;
using Eagles.LMS.Models;
using Eagles.LMS.Security;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eagles.LMS.Areas.Admission.Controllers
{

    [RouteArea("Admission")]
    [AuthorizeFilterAttribute]
    public class CategorysController : Controller
    {
        // GET: Admission/Categorys
        public ActionResult Index()
        {
            return View(new UnitOfWork().categoryManager.GetAll().ToList());
        }
        public ActionResult Edit(int id)
        {

            var catego = new UnitOfWork().categoryManager.GetBy(id);
            if (catego == null)
                return HttpNotFound();
            return View(catego);
        }
        [HttpPost]
        public ActionResult Edit(Category category, HttpPostedFileBase uploadattachments, HttpPostedFileBase uploadattachments_multi)
        {

            var _ctx = new UnitOfWork();



            RequestStatus requestStatus;
            if (uploadattachments != null && !
                uploadattachments.ContentType.CheckImageExtention())
            {

                requestStatus = new ManageRequestStatus().GetStatus(Status.GeneralError, "Attachment not supported ,Plz Upload Image Only");
            }
            else
            {
                if (uploadattachments_multi != null && !
                uploadattachments_multi.ContentType.CheckImageExtention())
                {

                    requestStatus = new ManageRequestStatus().GetStatus(Status.GeneralError, "Attachment not supported ,Plz Upload Image Only");
                }
                else
                {
                    //string _rendom, fileName, path;
                    if (uploadattachments != null)
                    {

                        string _rendom = System.Guid.NewGuid().ToString();

                        string extention = System.IO.Path.GetExtension(uploadattachments.FileName);

                        var fileName = DateTime.Now.ToString("dd_MM_yyyy_hh_mm_ss") + "_" + _rendom + extention;

                        var path = Path.Combine(Server.MapPath("~/attachments"), fileName);

                        uploadattachments.SaveAs(path);

                        category.MainImageOne = $"/attachments/{fileName}";
                     
                        requestStatus = new ManageRequestStatus().GetStatus(Status.Created);
                    }


                    if (uploadattachments_multi != null)
                    {

                        string _rendomtwo = System.Guid.NewGuid().ToString();
                        //var fileName = _rendom + Path.GetFileName(uploadattachments.FileName);

                        string extentiontwo = System.IO.Path.GetExtension(uploadattachments_multi.FileName);

                        var fileNametwo = DateTime.Now.ToString("dd_MM_yyyy_hh_mm_ss") + "_" + _rendomtwo + extentiontwo;


                        var pathtwo = Path.Combine(Server.MapPath("~/attachments"), fileNametwo);

                        uploadattachments_multi.SaveAs(pathtwo);

                        category.MainImageTwo = $"/attachments/{fileNametwo}";
                        requestStatus = new ManageRequestStatus().GetStatus(Status.Created);
                        //result = RedirectToAction(nameof(Create));
                    }

                    int userId = GetUserId();

                    _ctx.categoryManager.UpdateWithSave(category);

                    //var user = _ctx.UserManager.GetById(GetUserId());

                    requestStatus = new ManageRequestStatus().GetStatus(Status.Edited);


                }
            }

            TempData["RequestStatus"] = requestStatus;
            return View(category);

        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Category category, HttpPostedFileBase uploadattachments, HttpPostedFileBase uploadattachments_multi )
        {

            ActionResult result = View(category);

            if (ModelState.IsValid)
            {

                RequestStatus requestStatus;
                if (uploadattachments == null || uploadattachments.ContentLength == 0 || !
                    uploadattachments.ContentType.CheckImageExtention())
                {
                    requestStatus = new ManageRequestStatus().GetStatus(Status.GeneralError, "Attachment not supported ,Plz Upload Image Only");
                }
                else
                {


                    if (uploadattachments_multi == null || uploadattachments_multi.ContentLength == 0 || !
                    uploadattachments_multi.ContentType.CheckImageExtention())
                    {
                        requestStatus = new ManageRequestStatus().GetStatus(Status.GeneralError, "Attachment not supported two ,Plz Upload Image Only");

                    }
                    else
                    {
                        string _rendom = System.Guid.NewGuid().ToString();
                        string _rendomtwo = System.Guid.NewGuid().ToString();
                        //var fileName = _rendom + Path.GetFileName(uploadattachments.FileName);
                        string extention = System.IO.Path.GetExtension(uploadattachments.FileName);
                        string extentiontwo = System.IO.Path.GetExtension(uploadattachments_multi.FileName);
                        var fileName = DateTime.Now.ToString("dd_MM_yyyy_hh_mm_ss") + "_" + _rendom + extention;
                        var fileNametwo = DateTime.Now.ToString("dd_MM_yyyy_hh_mm_ss") + "_" + _rendomtwo + extentiontwo;

                        var path = Path.Combine(Server.MapPath("~/attachments"), fileName);
                        var pathtwo = Path.Combine(Server.MapPath("~/attachments"), fileNametwo);
                        uploadattachments.SaveAs(path);
                        uploadattachments_multi.SaveAs(pathtwo);
                        category.MainImageOne = $"/attachments/{fileName}";
                        category.MainImageTwo = $"/attachments/{fileNametwo}";
                        var _ctx = new UnitOfWork();

                        int userId = GetUserId();
                        category = _ctx.categoryManager.Add(category);
                        var user = _ctx.UserManager.GetById(GetUserId());



                        requestStatus = new ManageRequestStatus().GetStatus(Status.Created);
                        result = RedirectToAction(nameof(Create));

                    }

                }
                TempData["RequestStatus"] = requestStatus;



            }
            return result;

        }

        public int GetUserId()
        {
            var userFromSesstion = HttpContext.Session["User_Key"];
            return Convert.ToInt32(userFromSesstion);
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            UnitOfWork ctx = new UnitOfWork();
            var entity = ctx.categoryManager.GetBy(id);
            var user = ctx.UserManager.GetById(GetUserId());

            //ctx.logManager.Add(new log
            //{
            //    UserId = GetUserId(),
            //    ActionTime = DateTime.Now,
            //    EntityId = id,
            //    TableName = "Service",
            //    Action = "Delete:Service",
            //    LoginDate = user.LoginDate,
            //    LogoutDate = user.LogoutDate,
            //    ActionTitle = entity.TitleArabic
            //});


            ctx.categoryManager.Delete(entity);
            return Json(JsonRequestBehavior.AllowGet);
        }
    }
}

Eagles.LMS/Areas/Admission/Views/Categorys/Create.cshtml
@model Category
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admission/Views/Shared/_Layout.cshtml";
    var requestStatus = TempData.Peek("RequestStatus") as RequestStatus;
}

<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0 font-size-18">Add Service</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/Admission/Services">Home</a></li>
                        <li class="breadcrumb-item active">Service</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->
    <div class="row">
        @using (Html.BeginForm("Create", "categorys", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">



                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="row">


                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label class="form-label">Title Arabic</label>
                                            @Html.TextBoxFor(s => s.Name, null, new
                                       {
                                           @class = "form-control",
                                           placeholder = "Name"
                                       })
                                            @*@Html.ValidationMessageFor(s => s.TitleArabic)*@
                                        </div>
                                    </div>




                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label for="uploadattachments" class="form-label">Category Image One <span class="extiniosType">(jpg, png, peg, gif, jpg)</span><span class="extiniosType">(W:1500px, H:870px)</span></label>
                                            <input class="form-control" name="uploadattachments" type="file" id="uploadattachments">
                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label for="uploadattachments_multi" class="form-label">
                                                Category Image Two <span class="extiniosType">(jpg, png, peg, gif, jpg)</span><span class="extiniosType">(W:1500px, H:870px)</span>
                                            </label>
                                            <input class="form-control" name="uploadattachments_multi" type="file" id="uploadattachments_multi">
                                        </div>
                                    </div>


                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-check form-check-primary mb-3">
                                            @Html.CheckBoxFor(s => s.ShowInBodyType, new
                                       {
                                           @class = "form-check-input",
                                           @id = "ckekshow",
                                           placeholder = "Show In Body Type"
                                       })
                                            <label for="ckekshow" class="form-label" style="cursor:pointer;">Show In Body Type</label>
                                        </div>
                                    </div>




                                </div>
                            </div>

                        </div>


                    </div>
                </div>
            </div> <!-- end col -->


            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="foooterbuttons">
                            <button type="submit" onclick="return validate();" class="btn btn-success waves-effect waves-light">
                                <i class="bx bx-check-double font-size-16 align-middle me-2"></i> @Resources.Global.Save
                            </button>
                            <a href="/Admission/Categorys" class="btn btn-danger waves-effect waves-light">
                                <i class="fa fa-backspace back font-size-16 align-middle me-2"></i> @Resources.Global.Back
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        }
    </div>

</div>




@section EndBody{


    <script type="text/javascript">
        function validate() {
            var uploadattachments = document.getElementById('uploadattachments');
            var numb = $(uploadattachments)[0].files[0].size / 1024 / 1024;
            numb = numb.toFixed(2);
            if (numb > 3) {
                /*       alert('to big, maximum is 2MiB. You file size is: ' + numb + ' MiB');*/
                notify = $.notify({
                    message: 'Category Image One is to big, maximum is 3MiB. You file size is: ' + numb + ' MiB',

                }, {

                    type: '' == 'Created' ? "success" : "danger",
                    animate: {
                        enter: 'animated flipInY',
                        exit: 'animated flipOutX',
                    }
                });
                return false;
            }


            var uploadattachments_multi = document.getElementById('uploadattachments_multi');
            var numbTwo = $(uploadattachments_multi)[0].files[0].size / 1024 / 1024;
            numbTwo = numbTwo.toFixed(2);
            if (numbTwo > 3) {
                /*       alert('to big, maximum is 2MiB. You file size is: ' + numb + ' MiB');*/
                notify = $.notify({
                    message: 'Category Image Two Is to big, maximum is 3MiB. You file size is: ' + numbTwo + ' MiB',

                }, {

                    type: '' == 'Created' ? "success" : "danger",
                    animate: {
                        enter: 'animated flipInY',
                        exit: 'animated flipOutX',
                    }
                });
                return false;
            }


        }


    </script>



    @if (requestStatus != null)
    {



        <script>

              notify = $.notify({
                  message: '@requestStatus.Message',

              }, {

                      type: '@requestStatus.Status' == 'Created' ? "success" :"danger",
                      animate: {
                          enter: 'animated flipInY',
                          exit: 'animated flipOutX',
                      }
                  });
        </script>

        TempData.Remove("RequestStatus");
    }
}

Eagles.LMS/Areas/Admission/Views/Categorys/Edit.cshtml
@model Category
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admission/Views/Shared/_Layout.cshtml";
    var requestStatus = TempData.Peek("RequestStatus") as RequestStatus;

}


<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0 font-size-18">Add Service</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/Admission/Services">Home</a></li>
                        <li class="breadcrumb-item active">Service</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->
    <div class="row">
        @using (Html.BeginForm("Edit", "Categorys", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(s => s.ID)
            @Html.HiddenFor(s => s.MainImageOne)
            @Html.HiddenFor(s => s.MainImageTwo)
            @*@Html.HiddenFor(s => s.Name)*@

            @*@Html.HiddenFor(s => s.Status)*@



            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">



                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="row">


                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label class="form-label">Title Arabic</label>
                                            @Html.TextBoxFor(s => s.Name, null, new
                                       {
                                           @class = "form-control",
                                           placeholder = "Title Arabic"
                                       })
                                            @*@Html.ValidationMessageFor(s => s.TitleArabic)*@
                                        </div>
                                    </div>


                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label for="uploadattachments" class="form-label">Category Image One <span class="extiniosType">(jpg, png, peg, gif, jpg)</span><span class="extiniosType">(W:1500px, H:870px)</span></label>
                                            <input class="form-control" name="uploadattachments" type="file" id="uploadattachments">
                                        </div>
                                    </div>

                                    <div class="col-lg-12 col-md-12">
                                        <div class="mb-3">
                                            @if (Model.MainImageOne != null && Model.MainImageOne.Any())
                                            {
                                                <div id="box_mainImg" class="row">
                                                    <div class="col-lg-4">
                                                        <div class="ImagesGroup">
                                                            <div class="ImageItem">
                                                                <div class="Images">
                                                                    <img src="@Model.MainImageOne" />
                                                                </div>
                                                                @*<div class="DeletemainImg">
                                                                        <a class="btn_deleteMainImage" data-id="@Model.Id"><i class="bx bx-trash"></i></a>
                                                                    </div>*@
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            }


                                            @*<img style="max-width: auto; height: 210px " src="@Model.MainImage" />*@

                                        </div>
                                    </div>



                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label for="uploadattachments_multi" class="form-label">
                                                Category Image Two <span class="extiniosType">(jpg, png, peg, gif, jpg)</span><span class="extiniosType">(W:1500px, H:870px)</span>
                                            </label>
                                            <input class="form-control" name="uploadattachments_multi" type="file" id="uploadattachments_multi">
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="mb-3">
                                            <label class="form-label">
                                                Service Images
                                            </label>
                                        </div>
                                    </div>
                                    @if (Model.MainImageTwo != null && Model.MainImageTwo.Any())
                                    {
                                        <div class="ImagesGroup">
                                            <div class="row">

                                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 parentBox">
                                                    <div class="ImageItem">
                                                        <div class="Images">
                                                            <img src="@Model.MainImageTwo" />
                                                        </div>
                                                        @*<div class="DeleteBtn">
                                                                <a class=" btn_delete" data-id="@item.Id" href="#"><i class="bx bx-trash"></i></a>
                                                            </div>*@
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                        @*<table class="" style="display:none">
                                                <tr>
                                                    <th>IMG</th>
                                                    <th>Remove</th>
                                                </tr>
                                                @foreach (var item in Model.ServiceImages)
                                                {
                                                    <tr>
                                                        <td>
                                                            <img style="width:100px;height:100px" src="@item.Path" />
                                                        </td>
                                                        <td>


                                                        </td>
                                                    </tr>
                                                }
                                            </table>*@
                                    }



                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-check form-check-primary mb-3">
                                            @Html.CheckBoxFor(s => s.ShowInBodyType, new
                                       {
                                           @class = "form-check-input",
                                           @id = "ckekshow",
                                           placeholder = "Show In Body Type"
                                       })
                                            <label for="ckekshow" class="form-label" style="cursor:pointer;">Show In Body Type</label>

                                        </div>


                                    </div>



                                </div>
                            </div>

                        </div>


                    </div>
                </div>
            </div> <!-- end col -->


            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="foooterbuttons">
                            <button type="submit" onclick="return validate();" class="btn btn-success waves-effect waves-light">
                                <i class="bx bx-check-double font-size-16 align-middle me-2"></i> @Resources.Global.Save
                            </button>
                            <a href="/Admission/Categorys" class="btn btn-danger waves-effect waves-light">
                                <i class="fa fa-backspace back font-size-16 align-middle me-2"></i> @Resources.Global.Back
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        }
    </div>

</div>


@section EndBody{


    @if (requestStatus != null)
    {

        <script>

              notify = $.notify({
                  message: '@requestStatus.Message',

              }, {

                  type: '@requestStatus.Status' == 'Edited' ? "success" :"danger",
                      animate: {
                          enter: 'animated flipInY',
                          exit: 'animated flipOutX',
                      }
                  });
        </script>

        TempData.Remove("RequestStatus");
    }



    <script type="text/javascript">
        function validate() {
            var uploadattachments = document.getElementById('uploadattachments');
            var numb = $(uploadattachments)[0].files[0].size / 1024 / 1024;
            numb = numb.toFixed(2);
            if (numb > 3) {
                /*       alert('to big, maximum is 2MiB. You file size is: ' + numb + ' MiB');*/
                notify = $.notify({
                    message: 'Category Image One is to big, maximum is 3MiB. You file size is: ' + numb + ' MiB',

                }, {

                    type: '' == 'Created' ? "success" : "danger",
                    animate: {
                        enter: 'animated flipInY',
                        exit: 'animated flipOutX',
                    }
                });
                return false;
            }


            var uploadattachments_multi = document.getElementById('uploadattachments_multi');
            var numbTwo = $(uploadattachments_multi)[0].files[0].size / 1024 / 1024;
            numbTwo = numbTwo.toFixed(2);
            if (numbTwo > 3) {
                /*       alert('to big, maximum is 2MiB. You file size is: ' + numb + ' MiB');*/
                notify = $.notify({
                    message: 'Category Image Two Is to big, maximum is 3MiB. You file size is: ' + numbTwo + ' MiB',

                }, {

                    type: '' == 'Created' ? "success" : "danger",
                    animate: {
                        enter: 'animated flipInY',
                        exit: 'animated flipOutX',
                    }
                });
                return false;
            }


        }


    </script>

}