Eagles.LMS/Areas/Admission/Controllers/TypesController.cs
using Eagles.LMS.BLL;
using Eagles.LMS.Models;
using Eagles.LMS.Security;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eagles.LMS.Areas.Admission.Controllers
{
    [RouteArea("Admission")]
    [AuthorizeFilterAttribute]
    public class TypesController : Controller
    {
        // GET: Admission/Types
        public ActionResult Index()
        {
            return View(new UnitOfWork().typeManager.GetAll().ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Types types, HttpPostedFileBase uploadattachments, HttpPostedFileBase uploadattachments_multi)
        {

            ActionResult result = View(types);

            if (ModelState.IsValid)
            {

                RequestStatus requestStatus;
                if (uploadattachments == null || uploadattachments.ContentLength == 0 || !
                    uploadattachments.ContentType.CheckImageExtention())
                {
                    requestStatus = new ManageRequestStatus().GetStatus(Status.GeneralError, "Attachment not supported ,Plz Upload Image Only");
                }
                else
                {


                    if (uploadattachments_multi == null || uploadattachments_multi.ContentLength == 0 || !
                    uploadattachments_multi.ContentType.CheckImageExtention())
                    {
                        requestStatus = new ManageRequestStatus().GetStatus(Status.GeneralError, "Attachment not supported two ,Plz Upload Image Only");

                    }
                    else
                    {
                        string _rendom = System.Guid.NewGuid().ToString();
                        string _rendomtwo = System.Guid.NewGuid().ToString();
                        //var fileName = _rendom + Path.GetFileName(uploadattachments.FileName);
                        string extention = System.IO.Path.GetExtension(uploadattachments.FileName);
                        string extentiontwo = System.IO.Path.GetExtension(uploadattachments_multi.FileName);
                        var fileName = DateTime.Now.ToString("dd_MM_yyyy_hh_mm_ss") + "_" + _rendom + extention;
                        var fileNametwo = DateTime.Now.ToString("dd_MM_yyyy_hh_mm_ss") + "_" + _rendomtwo + extentiontwo;

                        var path = Path.Combine(Server.MapPath("~/attachments"), fileName);
                        var pathtwo = Path.Combine(Server.MapPath("~/attachments"), fileNametwo);
                        uploadattachments.SaveAs(path);
                        uploadattachments_multi.SaveAs(pathtwo);
                        types.MainImageOne = $"/attachments/{fileName}";
                        types.MainImageTwo = $"/attachments/{fileNametwo}";
                        var _ctx = new UnitOfWork();

                        int userId = GetUserId();
                        //category.UserCreateId = userId;
                        //category.CreateTime = DateTime.Now;
                        //category.UserEditId = userId;
                        //category.EditeTime = DateTime.Now;
                        types = _ctx.typeManager.Add(types);
                        var user = _ctx.UserManager.GetById(GetUserId());



                        requestStatus = new ManageRequestStatus().GetStatus(Status.Created);
                        result = RedirectToAction(nameof(Create));

                    }

                }
                TempData["RequestStatus"] = requestStatus;



            }
            return result;

        }



        public ActionResult Edit(int id)
        {

            var catego = new UnitOfWork().typeManager.GetBy(id);
            if (catego == null)
                return HttpNotFound();
            return View(catego);
            //return View();
        }
        [HttpPost]
        public ActionResult Edit(Types category, HttpPostedFileBase uploadattachments, HttpPostedFileBase uploadattachments_multi)
        {

            var _ctx = new UnitOfWork();



            RequestStatus requestStatus;
            if (uploadattachments != null && !
                uploadattachments.ContentType.CheckImageExtention())
            {

                requestStatus = new ManageRequestStatus().GetStatus(Status.GeneralError, "Attachment not supported ,Plz Upload Image Only");
            }
            else
            {
                if (uploadattachments_multi != null && !
                uploadattachments_multi.ContentType.CheckImageExtention())
                {

                    requestStatus = new ManageRequestStatus().GetStatus(Status.GeneralError, "Attachment not supported ,Plz Upload Image Only");
                }
                else
                {
                    //string _rendom, fileName, path;
                    if (uploadattachments != null)
                    {

                        //_rendom = new Random().Next(1, 99999999).ToString();

                        ////fileName = _rendom + Path.GetFileName(uploadattachments.FileName);
                        //string extention = System.IO.Path.GetExtension(uploadattachments.FileName);
                        //fileName = _rendom + extention;

                        //path = Path.Combine(Server.MapPath("~/attachments"), fileName);
                        //uploadattachments.SaveAs(path);
                        //category.MainImageOne = $"/attachments/{fileName}";




                        string _rendom = System.Guid.NewGuid().ToString();
                        string _rendomtwo = System.Guid.NewGuid().ToString();
                        //var fileName = _rendom + Path.GetFileName(uploadattachments.FileName);
                        string extention = System.IO.Path.GetExtension(uploadattachments.FileName);
                        string extentiontwo = System.IO.Path.GetExtension(uploadattachments_multi.FileName);
                        var fileName = DateTime.Now.ToString("dd_MM_yyyy_hh_mm_ss") + "_" + _rendom + extention;
                        var fileNametwo = DateTime.Now.ToString("dd_MM_yyyy_hh_mm_ss") + "_" + _rendomtwo + extentiontwo;

                        var path = Path.Combine(Server.MapPath("~/attachments"), fileName);
                        var pathtwo = Path.Combine(Server.MapPath("~/attachments"), fileNametwo);
                        uploadattachments.SaveAs(path);
                        uploadattachments_multi.SaveAs(pathtwo);
                        category.MainImageOne = $"/attachments/{fileName}";
                        category.MainImageTwo = $"/attachments/{fileNametwo}";
                        //var _ctx = new UnitOfWork();

                        //int userId = GetUserId();
                        //category = _ctx.categoryManager.Add(category);
                        //var user = _ctx.UserManager.GetById(GetUserId());



                        requestStatus = new ManageRequestStatus().GetStatus(Status.Created);
                        //result = RedirectToAction(nameof(Create));









                    }

                    int userId = GetUserId();

                    _ctx.typeManager.UpdateWithSave(category);
                    var user = _ctx.UserManager.GetById(GetUserId());






                    //if (uploadattachments_multi != null && uploadattachments_multi[0] != null)
                    //{
                    //    foreach (var item in uploadattachments_multi)
                    //    {
                    //        _rendom = new Random().Next(1, 99999999).ToString();

                    //        //fileName = _rendom + Path.GetFileName(item.FileName);
                    //        string extention = System.IO.Path.GetExtension(item.FileName);
                    //        fileName = _rendom + extention;

                    //        path = Path.Combine(Server.MapPath("~/attachments"), fileName);
                    //        item.SaveAs(path);
                    //        _ctx.ServiceImagesManager.Add(new ServiceImages
                    //        {

                    //            ServiceId = service.Id,
                    //            Path = $"/attachments/{fileName}",

                    //        });

                    //    }
                    //}


                    requestStatus = new ManageRequestStatus().GetStatus(Status.Edited);




                }
            }

            TempData["RequestStatus"] = requestStatus;
            //service.ServiceImages = _ctx.ServiceImagesManager.GetAll().Where(s => s.ServiceId == service.Id).ToList();
            return View(category);

        }



        public int GetUserId()
        {
            var userFromSesstion = HttpContext.Session["User_Key"];
            return Convert.ToInt32(userFromSesstion);
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            UnitOfWork ctx = new UnitOfWork();
            var entity = ctx.typeManager.GetBy(id);
            var user = ctx.UserManager.GetById(GetUserId());

            //ctx.logManager.Add(new log
            //{
            //    UserId = GetUserId(),
            //    ActionTime = DateTime.Now,
            //    EntityId = id,
            //    TableName = "Service",
            //    Action = "Delete:Service",
            //    LoginDate = user.LoginDate,
            //    LogoutDate = user.LogoutDate,
            //    ActionTitle = entity.TitleArabic
            //});


            ctx.typeManager.Delete(entity);
            return Json(JsonRequestBehavior.AllowGet);
        }
    }
}

Eagles.LMS/Areas/Admission/Views/Types/Create.cshtml
@model Types
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admission/Views/Shared/_Layout.cshtml";
    var requestStatus = TempData.Peek("RequestStatus") as RequestStatus;
    var categories = new Eagles.LMS.BLL.UnitOfWork().categoryManager.GetAllBind();
}

<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0 font-size-18">Add Service</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/Admission/Services">Home</a></li>
                        <li class="breadcrumb-item active">Service</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->
    <div class="row">
        @using (Html.BeginForm("Create", "Types", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">



                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="row">


                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label class="form-label">Title Arabic</label>
                                            @Html.TextBoxFor(s => s.Name, null, new
                                       {
                                           @class = "form-control",
                                           placeholder = "Name"
                                       })
                                            @*@Html.ValidationMessageFor(s => s.TitleArabic)*@
                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label class="form-label">categories</label>
                                            @Html.DropDownListFor(x => Model.CategoryID, new SelectList(categories,
                                           "Id", "Name"), htmlAttributes: new { @class = "form-control select2" })


                                        </div>
                                    </div>


                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label for="uploadattachments" class="form-label">Type  Image One <span class="extiniosType">(jpg, png, peg, gif, jpg)</span><span class="extiniosType">(W:1500px, H:870px)</span></label>
                                            <input class="form-control" name="uploadattachments" type="file" id="uploadattachments">
                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label for="uploadattachments_multi" class="form-label">
                                                Type  Image Two <span class="extiniosType">(jpg, png, peg, gif, jpg)</span><span class="extiniosType">(W:1500px, H:870px)</span>
                                            </label>
                                            <input class="form-control" name="uploadattachments_multi" type="file" id="uploadattachments_multi">
                                        </div>
                                    </div>





                                </div>
                            </div>

                        </div>


                    </div>
                </div>
            </div> <!-- end col -->


            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="foooterbuttons">
                            <button type="submit" onclick="return validate();" class="btn btn-success waves-effect waves-light">
                                <i class="bx bx-check-double font-size-16 align-middle me-2"></i> @Resources.Global.Save
                            </button>
                            <a href="/Admission/Category" class="btn btn-danger waves-effect waves-light">
                                <i class="fa fa-backspace back font-size-16 align-middle me-2"></i> @Resources.Global.Back
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        }
    </div>

</div>



@section EndBody{

    <script type="text/javascript">
        function validate() {
            var uploadattachments = document.getElementById('uploadattachments');
            var numb = $(uploadattachments)[0].files[0].size / 1024 / 1024;
            numb = numb.toFixed(2);
            if (numb > 3) {
                /*       alert('to big, maximum is 2MiB. You file size is: ' + numb + ' MiB');*/
                notify = $.notify({
                    message: 'Type  Image One is to big, maximum is 3MiB. You file size is: ' + numb + ' MiB',

                }, {

                    type: '' == 'Created' ? "success" : "danger",
                    animate: {
                        enter: 'animated flipInY',
                        exit: 'animated flipOutX',
                    }
                });
                return false;
            }


            var uploadattachments_multi = document.getElementById('uploadattachments_multi');
            var numbTwo = $(uploadattachments_multi)[0].files[0].size / 1024 / 1024;
            numbTwo = numbTwo.toFixed(2);
            if (numbTwo > 3) {
                /*       alert('to big, maximum is 2MiB. You file size is: ' + numb + ' MiB');*/
                notify = $.notify({
                    message: 'Type  Image Two Is to big, maximum is 3MiB. You file size is: ' + numbTwo + ' MiB',

                }, {

                    type: '' == 'Created' ? "success" : "danger",
                    animate: {
                        enter: 'animated flipInY',
                        exit: 'animated flipOutX',
                    }
                });
                return false;
            }


        }


    </script>


    @if (requestStatus != null)
    {


        <script>

              notify = $.notify({
                  message: '@requestStatus.Message',

              }, {

                      type: '@requestStatus.Status' == 'Created' ? "success" :"danger",
                      animate: {
                          enter: 'animated flipInY',
                          exit: 'animated flipOutX',
                      }
                  });
        </script>

        TempData.Remove("RequestStatus");
    }
}

Eagles.LMS/Areas/Admission/Views/Types/Edit.cshtml
@model Types
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admission/Views/Shared/_Layout.cshtml";
    var requestStatus = TempData.Peek("RequestStatus") as RequestStatus;
    var categories = new Eagles.LMS.BLL.UnitOfWork().categoryManager.GetAllBind();

}


<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0 font-size-18">Add Service</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="/Admission/Services">Home</a></li>
                        <li class="breadcrumb-item active">Service</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <!-- end page title -->
    <div class="row">
        @using (Html.BeginForm("Edit", "Types", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(s => s.ID)
            @Html.HiddenFor(s => s.MainImageOne)
            @Html.HiddenFor(s => s.MainImageTwo)
            @*@Html.HiddenFor(s => s.CreateTime)
                @Html.HiddenFor(s => s.UserCreateId)*@
            @*@Html.HiddenFor(s => s.Status)*@



            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">



                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="row">


                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label class="form-label">Title Arabic</label>
                                            @Html.TextBoxFor(s => s.Name, null, new
                                       {
                                           @class = "form-control",
                                           placeholder = "Title Arabic"
                                       })
                                            @*@Html.ValidationMessageFor(s => s.TitleArabic)*@
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label class="form-label">categories</label>
                                            @Html.DropDownListFor(x => Model.CategoryID, new SelectList(categories,
                                           "Id", "Name"), htmlAttributes: new { @class = "form-control select2" })


                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label for="uploadattachments" class="form-label">Main Image <span class="extiniosType">(jpg, png, peg, gif, jpg)</span><span class="extiniosType">(W:1500px, H:870px)</span></label>
                                            <input class="form-control" name="uploadattachments" type="file" id="uploadattachments">
                                        </div>
                                    </div>

                                    <div class="col-lg-12 col-md-12">
                                        <div class="mb-3">
                                            @if (Model.MainImageOne != null && Model.MainImageOne.Any())
                                            {
                                                <div id="box_mainImg" class="row">
                                                    <div class="col-lg-4">
                                                        <div class="ImagesGroup">
                                                            <div class="ImageItem">
                                                                <div class="Images">
                                                                    <img src="@Model.MainImageOne" />
                                                                </div>
                                                                @*<div class="DeletemainImg">
                                                                        <a class="btn_deleteMainImage" data-id="@Model.Id"><i class="bx bx-trash"></i></a>
                                                                    </div>*@
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            }


                                            @*<img style="max-width: auto; height: 210px " src="@Model.MainImage" />*@

                                        </div>
                                    </div>



                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="mb-3">
                                            <label for="uploadattachments_multi" class="form-label">
                                                Service Images [Optional] <span class="extiniosType">(jpg, png, peg, gif, jpg)</span><span class="extiniosType">(W:1500px, H:870px)</span>
                                            </label>
                                            <input class="form-control" name="uploadattachments_multi" type="file" id="uploadattachments_multi">
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="mb-3">
                                            <label class="form-label">
                                                Service Images
                                            </label>
                                        </div>
                                    </div>
                                    @if (Model.MainImageTwo != null && Model.MainImageTwo.Any())
                                    {
                                        <div class="ImagesGroup">
                                            <div class="row">

                                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 parentBox">
                                                    <div class="ImageItem">
                                                        <div class="Images">
                                                            <img src="@Model.MainImageTwo" />
                                                        </div>
                                                        @*<div class="DeleteBtn">
                                                                <a class=" btn_delete" data-id="@item.Id" href="#"><i class="bx bx-trash"></i></a>
                                                            </div>*@
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                        @*<table class="" style="display:none">
                                                <tr>
                                                    <th>IMG</th>
                                                    <th>Remove</th>
                                                </tr>
                                                @foreach (var item in Model.ServiceImages)
                                                {
                                                    <tr>
                                                        <td>
                                                            <img style="width:100px;height:100px" src="@item.Path" />
                                                        </td>
                                                        <td>


                                                        </td>
                                                    </tr>
                                                }
                                            </table>*@
                                    }





                                </div>
                            </div>

                        </div>


                    </div>
                </div>
            </div> <!-- end col -->


            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="foooterbuttons">
                            <button type="submit" onclick="return validate();" class="btn btn-success waves-effect waves-light">
                                <i class="bx bx-check-double font-size-16 align-middle me-2"></i> @Resources.Global.Save
                            </button>
                            <a href="/Admission/Services" class="btn btn-danger waves-effect waves-light">
                                <i class="fa fa-backspace back font-size-16 align-middle me-2"></i> @Resources.Global.Back
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        }
    </div>

</div>


@section EndBody{



    <script type="text/javascript">
        function validate() {
            var uploadattachments = document.getElementById('uploadattachments');
            var numb = $(uploadattachments)[0].files[0].size / 1024 / 1024;
            numb = numb.toFixed(2);
            if (numb > 3) {
                /*       alert('to big, maximum is 2MiB. You file size is: ' + numb + ' MiB');*/
                notify = $.notify({
                    message: 'Main Car Img is to big, maximum is 3MiB. You file size is: ' + numb + ' MiB',

                }, {

                    type: '' == 'Created' ? "success" : "danger",
                    animate: {
                        enter: 'animated flipInY',
                        exit: 'animated flipOutX',
                    }
                });
                return false;
            }


            var uploadattachments_multi = document.getElementById('uploadattachments_multi');
            var numbTwo = $(uploadattachments_multi)[0].files[0].size / 1024 / 1024;
            numbTwo = numbTwo.toFixed(2);
            if (numbTwo > 3) {
                /*       alert('to big, maximum is 2MiB. You file size is: ' + numb + ' MiB');*/
                notify = $.notify({
                    message: 'Car Images Item Is to big, maximum is 3MiB. You file size is: ' + numbTwo + ' MiB',

                }, {

                    type: '' == 'Created' ? "success" : "danger",
                    animate: {
                        enter: 'animated flipInY',
                        exit: 'animated flipOutX',
                    }
                });
                return false;
            }


        }


    </script>


    @if (requestStatus != null)
    {

        <script>

              notify = $.notify({
                  message: '@requestStatus.Message',

              }, {

                  type: '@requestStatus.Status' == 'Edited' ? "success" :"danger",
                      animate: {
                          enter: 'animated flipInY',
                          exit: 'animated flipOutX',
                      }
                  });
        </script>

        TempData.Remove("RequestStatus");
    }
}